version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    networks:
      - app-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./notebooks:/notebooks
      - ./app:/app
    working_dir: /notebooks
    ports:
      - "8888:8888"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --NotebookApp.token='' --notebook-dir=/notebooks
    networks:
      - app-net

networks:
  app-net:
